# Generated by Django 5.2.8 on 2025-12-09 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
        ('token_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tokens', to='doctors.doctor'),
        ),
    ]
