# Generated by Django 5.2.8 on 2025-12-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_number',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
