# Generated by Django 5.2.8 on 2025-12-12 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_alter_hospital_contact_phone_and_more'),
        ('token_queue', '0002_alter_token_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_tokens', to='hospitals.hospital'),
        ),
    ]
