# Generated by Django 5.2.8 on 2026-02-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_queue', '0002_alter_token_token_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='token_qr/'),
        ),
    ]
