# Generated by Django 5.2.8 on 2026-02-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_queue', '0003_token_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_service', 'In Service'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
