# Generated by Django 5.2.8 on 2026-03-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_queue', '0004_alter_token_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['token_number']},
        ),
        migrations.AddField(
            model_name='token',
            name='source',
            field=models.CharField(choices=[('online', 'Online Booking'), ('walkin', 'Walk-in'), ('kiosk', 'Self Kiosk')], default='online', max_length=20),
        ),
    ]
