# Generated by Django 5.2.8 on 2026-03-09 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_user'),
        ('token_queue', '0005_alter_token_options_token_source'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('doctor', 'token_number', 'booked_at')},
        ),
    ]
