# Generated by Django 5.2.8 on 2026-03-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_queue', '0006_alter_token_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='prefix',
            field=models.CharField(blank=True, editable=False, max_length=5),
        ),
    ]
