# Generated by Django 5.2.8 on 2026-03-13 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospital_admin'),
        ('users', '0005_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='hospitals.hospital'),
        ),
    ]
