# Generated by Django 5.2.8 on 2025-12-09 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_doctor_hospital'),
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_tokens', to='doctors.doctor'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
