# Generated by Django 5.2.8 on 2025-12-12 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_token_doctor_delete_doctor'),
        ('hospitals', '0002_alter_hospital_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_tokens', to='hospitals.hospital'),
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
