# Generated by Django 5.2.8 on 2025-12-13 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_token_hospital_delete_hospital'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='patients.patient'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
