# Generated by Django 5.2.8 on 2026-03-12 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_latitude_hospital_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='admin',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'hospital_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hospitals', to=settings.AUTH_USER_MODEL),
        ),
    ]
