#hospitals/0004_hospital_profile_picture.py
# Generated by Django 5.2.8 on 2026-03-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospital_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
