# Generated by Django 5.2.8 on 2025-12-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_add_hospital_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
