# Generated by Django 5.2.8 on 2025-12-12 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_fill_hospital_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='contact_phone',
            field=models.CharField(max_length=10, null=True, blank=True, db_column='contact_number'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
