# Generated by Django 5.2.8 on 2025-12-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_alter_hospital_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='contact_phone',
            field=models.CharField(blank=True, db_column='contact_number', help_text='Primary contact number (stored in DB column contact_number)', max_length=30, null=True),
        ),
    ]
