#doctors/0003_doctor_is_paused_doctor_profile_picture.py
# Generated by Django 5.2.8 on 2026-03-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_profiles/'),
        ),
    ]
